-- YAMA AI Legal Database Export
-- Generated: 2026-03-15T18:11:33.521733
-- Records: 87

CREATE TABLE IF NOT EXISTS law_sections (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    act_name VARCHAR(500) NOT NULL,
    section_number VARCHAR(50) NOT NULL,
    title VARCHAR(1000) NOT NULL,
    description TEXT NOT NULL,
    keywords TEXT,
    category VARCHAR(100) NOT NULL DEFAULT 'general',
    punishment TEXT,
    old_law_reference VARCHAR(500),
    jurisdiction VARCHAR(50) DEFAULT 'central',
    state_name VARCHAR(200),
    law_type VARCHAR(100) DEFAULT 'act',
    source_url VARCHAR(2000),
    content_hash VARCHAR(64),
    is_active BOOLEAN DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nagarik Suraksha Sanhita, 2023', '173', 'FIR - Information in cognizable cases', 'Every information relating to the commission of a cognizable offence, if given orally to an officer in charge of a police station, shall be reduced to writing by him or under his direction, and be read over to the informant; and every such information, whether given in writing or reduced to writing, shall be signed by the person giving it.', 'fir, first information report, police complaint, cognizable offence, police station, information, cognizable, cases, every, relating, commission, offence, given', 'criminal', NULL, 'Code of Criminal Procedure, Section 154', 'central', NULL, 'act', NULL, '542a4eaf4f5e1b0b995a0f0ef9939f3b94beab0adc2e8c96670ba4e28077b85c');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nagarik Suraksha Sanhita, 2023', '175', 'Police officer''s power to investigate cognizable case', 'Any officer in charge of a police station may, without the order of a Magistrate, investigate any cognizable case which a court having jurisdiction over the local area within the limits of such station would have power to inquire into or try.', 'investigation, police power, cognizable case, inquiry, police station, police, officer, power, investigate, cognizable, case, charge, station', 'criminal', NULL, 'Code of Criminal Procedure, Section 156', 'central', NULL, 'act', NULL, '775accad33649bbe7fe890bbd5c77b0c9fc563b59542cf36fe6ac1a6465cd7e5');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nagarik Suraksha Sanhita, 2023', '187', 'Procedure when investigation cannot be completed in twenty-four hours', 'Whenever any person is arrested and detained in custody, and it appears that the investigation cannot be completed within the period of twenty-four hours, the officer in charge of the police station shall transmit to the nearest Judicial Magistrate a copy of the entries in the diary and shall also forward the accused to such Magistrate.', 'arrest, detention, 24 hours, judicial magistrate, police custody, remand, procedure, when, investigation, cannot, completed, twenty, four, hours', 'criminal', NULL, 'Code of Criminal Procedure, Section 167', 'central', NULL, 'act', NULL, '5dee9c502f872f888c618375cb3cb540ba70181887f7200a0deb70b79be2f5c6');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nagarik Suraksha Sanhita, 2023', '210', 'Chargesheet - Report of police officer on completion of investigation', 'Every investigation shall be completed without unnecessary delay and the report under this section shall be forwarded to the Magistrate. If there is sufficient evidence, a chargesheet shall be filed. The investigation shall be completed within sixty days from the date of first information report for offences punishable with imprisonment up to three years, and ninety days for other offences.', 'chargesheet, investigation report, police report, magistrate, fir closure, report, police, officer, completion, investigation, every, completed', 'criminal', NULL, 'Code of Criminal Procedure, Section 173', 'central', NULL, 'act', NULL, '22b8e94612b41408d6aa0d234b52abdb08f90875bb4add52d561d8d0839102aa');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nagarik Suraksha Sanhita, 2023', '360', 'Order to pay compensation', 'When a Court imposes a sentence of fine or a sentence of which fine forms a part, the Court may order the whole or any part of the fine recovered to be applied in the payment to any person of compensation for any loss or injury caused by the offence.', 'compensation, victim compensation, fine, sentence, court order, loss, order, when, court, imposes, forms', 'criminal', NULL, 'Code of Criminal Procedure, Section 357', 'central', NULL, 'act', NULL, '996de5a18c3a74661b5033905fd34e805617ad76831c2a34f914c450a772ebb1');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nagarik Suraksha Sanhita, 2023', '480', 'Bail in case of bailable offence', 'When any person other than a person accused of a non-bailable offence is arrested or detained without warrant by an officer in charge of a police station, or appears or is brought before a Court, and is prepared at any time while in the custody of such officer or at any stage of the proceeding before such Court to give bail, such person shall be released on bail.', 'bail, bailable offence, release, surety, police custody, court, case, bailable, offence, when, person, other, than', 'criminal', NULL, 'Code of Criminal Procedure, Section 436', 'central', NULL, 'act', NULL, '8fd01aa20d44dbf6ef0b9092874eb8ad1abe01cc5d43b501e34c6ceac1065cad');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nagarik Suraksha Sanhita, 2023', '482', 'Bail in case of non-bailable offence', 'When any person accused of, or suspected of, the commission of any non-bailable offence is arrested or detained without warrant by an officer in charge of a police station or appears or is brought before a Court other than the High Court or Court of Session, he may be released on bail. The court shall consider the nature and gravity of the offence, criminal antecedents of the applicant, and possibility of his fleeing from justice.', 'bail, non-bailable offence, anticipatory bail, court discretion, surety, case, bailable, offence, when, person, accused, suspected', 'criminal', NULL, 'Code of Criminal Procedure, Section 437', 'central', NULL, 'act', NULL, '1fd4068b6b3cbb3940a6ba296ab8713217152df462cbc40e6e72a69e3ee10fff');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nagarik Suraksha Sanhita, 2023', '483', 'Anticipatory Bail', 'Where any person has reason to believe that he may be arrested on accusation of having committed a non-bailable offence, he may apply to the High Court or the Court of Session for a direction that in the event of such arrest, he shall be released on bail.', 'anticipatory bail, pre-arrest bail, non-bailable, high court, sessions court, anticipatory, bail, where, person, reason, believe, arrested, accusation', 'criminal', NULL, 'Code of Criminal Procedure, Section 438', 'central', NULL, 'act', NULL, '503777e719f763aaddad0d739bfbf05b0f4df1ed4d3a3d36b8fbf4d4ea0fd2ed');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nagarik Suraksha Sanhita, 2023', '528', 'Inherent powers of High Court', 'Nothing in this Sanhita shall be deemed to limit or affect the inherent powers of the High Court to make such orders as may be necessary to give effect to any order under this Sanhita, or to prevent abuse of the process of any Court or otherwise to secure the ends of justice.', 'inherent powers, high court, quashing, justice, abuse of process, section 482, inherent, powers, high, court, nothing, sanhita, deemed, limit', 'criminal', NULL, 'Code of Criminal Procedure, Section 482', 'central', NULL, 'act', NULL, '0142bd93621ffe270d0506e5f48a381a62949bde83582f79f231ea4fbf12daba');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '100', 'Murder', 'Whoever causes death by doing an act with the intention of causing death, or with the intention of causing such bodily injury as is likely to cause death, or with the knowledge that he is likely by such act to cause death, commits the offence of murder.', 'murder, homicide, death, killing, intention to kill, whoever, causes, doing, intention, causing, bodily', 'criminal', 'Death or imprisonment for life, and shall also be liable to fine.', 'Indian Penal Code, Section 302', 'central', NULL, 'act', NULL, 'fa87e5bdc6a552e46042c416e15bbaae7e3be1dadf6801fb45a9456d57f3b4d7');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '101', 'Culpable Homicide not amounting to murder', 'Whoever causes death by doing an act with the intention of causing death, or with the intention of causing such bodily injury as is likely to cause death, or with the knowledge that he is likely by such act to cause death, but without premeditation in a sudden fight in the heat of passion upon a sudden quarrel.', 'culpable homicide, manslaughter, death, sudden fight, heat of passion, culpable, homicide, amounting, murder, whoever, causes, doing', 'criminal', 'Imprisonment for life, or imprisonment up to 10 years, and fine.', 'Indian Penal Code, Section 304', 'central', NULL, 'act', NULL, '4cdb45425b860c1232ea8061cb9c27fda80fe6c75275129e9a540969cf11b8de');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '103', 'Punishment for murder', 'Whoever commits murder shall be punished with death, or imprisonment for life, and shall also be liable to fine. The court shall record special reasons for not imposing death sentence in cases involving extreme brutality.', 'murder punishment, death penalty, life imprisonment, capital punishment, punishment, murder, whoever, commits, punished, death, imprisonment, life', 'criminal', 'Death or imprisonment for life, and fine.', 'Indian Penal Code, Section 302', 'central', NULL, 'act', NULL, '43099efc17c65e08056a5ce419c23c455178cf1930d8820b377d4188998b74bc');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '105', 'Dowry Death', 'Where the death of a woman is caused by any burns or bodily injury or occurs otherwise than under normal circumstances within seven years of her marriage and it is shown that soon before her death she was subjected to cruelty or harassment by her husband or any relative of her husband for, or in connection with, any demand for dowry, such death shall be called dowry death.', 'dowry death, dowry harassment, bride burning, marital cruelty, seven years, dowry, death, where, woman, caused, burns, bodily, injury', 'criminal', 'Imprisonment not less than seven years but which may extend to imprisonment for life.', 'Indian Penal Code, Section 304B', 'central', NULL, 'act', NULL, '6ed9dc7abd9f9e4ded6b69e4ca16bbeb488ab0e5e0d07f815b993f3be205d49a');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '109', 'Attempt to murder', 'Whoever does any act with such intention or knowledge and under such circumstances that, if he by that act caused death, he would be guilty of murder, shall be punished with imprisonment of either description for a term which may extend to ten years, and shall also be liable to fine.', 'attempt to murder, attempted homicide, intent to kill, assault, attempt, murder, whoever, does, intention, knowledge, circumstances, caused', 'criminal', 'Imprisonment up to 10 years and fine. If hurt is caused, up to imprisonment for life.', 'Indian Penal Code, Section 307', 'central', NULL, 'act', NULL, '22abb7a3963ddbf1fc6da207727ffc6a6dc1f536558d0579caaa06bbd18a8b94');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '111', 'Organized Crime', 'Any continuing unlawful activity including kidnapping, robbery, vehicle theft, extortion, land grabbing, contract killing, economic offence, cyber-crimes committed by a member of such group or gang individually or jointly, either as a member of such group or gang or on behalf of such group or gang, and commission of such offence shall be a cognizable and non-bailable offence punishable under this Act.', 'organized crime, gang, syndicate, continuing unlawful activity, mafia, criminal group, organized, crime, continuing, unlawful, activity, including, kidnapping, robbery', 'criminal', 'If offence results in death: death or imprisonment for life and fine of not less than ten lakh. Otherwise: imprisonment not less than five years extendable to life and fine not less than five lakh.', 'No equivalent in IPC. New provision in BNS 2023.', 'central', NULL, 'act', NULL, 'cc16062800788fc8b2023661d2a3d0559ea785c0e5dee337b47bf20b7c8c0787');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '112', 'Petty Organized Crime', 'Whoever, being a member of a group or gang, either individually or jointly, commits any of the following offences, including theft, snatching, cheating, unauthorized selling of tickets, unauthorized betting or gambling, selling of public examination question papers, shall be guilty of petty organized crime.', 'petty crime, snatching, ticket selling, gambling, organized group, minor offence, petty, organized, crime, whoever, being, member, group, gang', 'criminal', 'Imprisonment from one to seven years, and fine.', 'No equivalent in IPC. New provision in BNS 2023.', 'central', NULL, 'act', NULL, 'aeebbafb7d07e5997af2b5895288c16972b19ae34f8cbc05764618388884988c');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '113', 'Terrorist Act', 'Whoever does any act with the intent to threaten or likely to threaten the unity, integrity, sovereignty, security, or economic security of India, or with the intent to strike terror or likely to strike terror in the people or any section of the people in India or in any foreign country.', 'terrorism, terrorist act, national security, bomb, explosive, threat to unity, terrorist, whoever, does, intent, threaten, likely, unity, integrity', 'criminal', 'Death or imprisonment for life, and shall also be liable to fine, if such act has resulted in death. Otherwise: imprisonment not less than five years extendable to life, and fine not less than five lakh.', 'UAPA provisions. New addition to BNS 2023.', 'central', NULL, 'act', NULL, 'a15e4e310578df7c38572349ba34204e4085321deac15c98b3b717be085cfb97');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '115', 'Voluntarily causing hurt', 'Whoever does any act with the intention of thereby causing hurt to any person, or with the knowledge that he is likely thereby to cause hurt to any person, and does thereby cause hurt to any person, is said to voluntarily cause hurt.', 'hurt, assault, bodily harm, injury, violence, voluntarily, causing, whoever, does, intention, thereby, person', 'criminal', 'Imprisonment up to one year, or fine up to ten thousand rupees, or both.', 'Indian Penal Code, Section 323', 'central', NULL, 'act', NULL, 'f73e2f0088acadcdb2fa54e752fcf787a44a8c2111aafc7b287dd6936ff1c3e0');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '117', 'Voluntarily causing grievous hurt', 'Whoever voluntarily causes hurt, if the hurt which he intends to cause or knows himself to be likely to cause is grievous hurt, and if the hurt which he causes is grievous hurt, is said voluntarily to cause grievous hurt. Grievous hurt includes emasculation, permanent privation of sight, hearing, or any member or joint, fracture or dislocation of bone.', 'grievous hurt, serious injury, fracture, permanent damage, bodily harm, voluntarily, causing, grievous, hurt, whoever, causes, intends, cause', 'criminal', 'Imprisonment up to seven years, and fine.', 'Indian Penal Code, Section 325', 'central', NULL, 'act', NULL, 'fb84256730bb9bcdf325f21c76315f1ecdba2f49a893bcae3579e4578ef9de72');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '125', 'Act endangering life or personal safety of others', 'Whoever does any act so rashly or negligently as to endanger human life or the personal safety of others, shall be punished. Includes rash driving, negligent acts causing danger to public.', 'rash act, negligence, endangering life, personal safety, rash driving, endangering, life, personal, safety, others, whoever, does, rashly', 'criminal', 'Imprisonment up to three months, or fine up to two thousand five hundred rupees, or both.', 'Indian Penal Code, Section 336', 'central', NULL, 'act', NULL, '2601c2e4c837849b8ff207cb613ba0ded653aacf857be3ae1cf03d6133258fa4');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '152', 'Acts endangering sovereignty, unity and integrity of India', 'Whoever, purposely or knowingly, by words, either spoken or written, or by signs, or by visible representation, or by electronic communication or by use of financial means, or otherwise, excites or attempts to excite, secession or armed rebellion or subversive activities, or encourages feelings of separatist activities or endangers sovereignty or unity and integrity of India.', 'sedition replacement, sovereignty, unity, integrity, separatism, anti-national, subversion, acts, endangering, india, whoever, purposely', 'criminal', 'Imprisonment for life, or imprisonment up to seven years, and fine.', 'Indian Penal Code, Section 124A (Sedition — now replaced).', 'central', NULL, 'act', NULL, '73c5a413e2cc0508f12dbe360676f454a2d304233a84e163c2654daae7c130f4');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '196', 'Promoting enmity between different groups', 'Whoever promotes or attempts to promote, on grounds of religion, race, place of birth, residence, language, caste or community or any other ground whatsoever, disharmony or feelings of enmity, hatred or ill-will between different religious, racial, language or regional groups or castes or communities.', 'enmity, hatred, communal, religion, caste, disharmony, hate speech, incitement, promoting, between, different, groups, whoever, promotes, attempts', 'criminal', 'Imprisonment up to three years, or fine, or both.', 'Indian Penal Code, Section 153A', 'central', NULL, 'act', NULL, 'a9a45171583be240b1d122c39001fb5a0db24663032c1c8ce8d069285ca182b9');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '263', 'Public nuisance', 'A person is guilty of a public nuisance who does any act or is guilty of an illegal omission which causes any common injury, danger or annoyance to the public or to the people in general who dwell or occupy property in the vicinity.', 'public nuisance, common injury, annoyance, neighbourhood, pollution, noise, public, nuisance, person, guilty, does, illegal, omission, causes', 'criminal', 'Fine up to one thousand rupees.', 'Indian Penal Code, Section 268', 'central', NULL, 'act', NULL, 'bf0fe0351574ffd34d85f6146818c407d883b727eeb72329e9f40fcb92e3c6cb');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '281', 'Rash driving or riding on a public way', 'Whoever drives any vehicle, or rides, on any public way in a manner so rash or negligent as to endanger human life, or to be likely to cause hurt or injury to any other person.', 'rash driving, negligent driving, road accident, traffic offence, public way, rash, driving, riding, public, whoever, drives, vehicle, rides', 'criminal', 'Imprisonment up to six months, or fine up to one thousand rupees, or both.', 'Indian Penal Code, Section 279', 'central', NULL, 'act', NULL, 'ee713c8d7eece2a9652d3097823db9ca765cfbd435531193be95faa9130a42cb');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '285', 'Causing death by negligence', 'Whoever causes the death of any person by doing any rash or negligent act not amounting to culpable homicide.', 'death by negligence, accidental death, rash act, negligence, manslaughter, causing, death, whoever, causes, person, doing, rash', 'criminal', 'Imprisonment up to five years, and fine. If by rash or negligent act: up to imprisonment for life.', 'Indian Penal Code, Section 304A', 'central', NULL, 'act', NULL, '2cf55c0a9621fac555eb3ecbc50f2098cc962d86ff23cb4c4e08f2998a39cd70');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '303', 'Theft', 'Whoever, intending to take dishonestly any moveable property out of the possession of any person without that person''s consent, moves that property in order to such taking, is said to commit theft.', 'theft, stealing, dishonest taking, moveable property, stolen, whoever, intending, take, dishonestly, moveable, property, possession', 'criminal', 'Imprisonment up to three years, or fine, or both.', 'Indian Penal Code, Section 378', 'central', NULL, 'act', NULL, '612a4c92db2749c408de713433b25440090b9ef29abc8ea7588c8c55c6c65f71');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '304', 'Snatching', 'Whoever commits theft, with the intent to cause hurt or fear of hurt to any person, by suddenly or quickly or forcibly seizing or securing or grabbing from any person any moveable property, is said to commit snatching.', 'snatching, chain snatching, mobile snatching, theft with force, sudden seizure, whoever, commits, theft, intent, cause, hurt, fear', 'criminal', 'Imprisonment up to three years, and shall also be liable to fine.', 'No equivalent in IPC. New provision in BNS 2023.', 'central', NULL, 'act', NULL, '4c7309381ec95e552670f1b2999a108b3c7ea0c3119d0b30dcfb48af8620f8d2');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '305', 'Robbery', 'In all robbery there is either theft or extortion. When theft is robbery: theft is robbery if, in order to the committing of the theft, or in committing the theft, or in carrying away or attempting to carry away property obtained by the theft, the offender voluntarily causes or attempts to cause death or hurt or wrongful restraint, or fear of instant death, hurt, or wrongful restraint.', 'robbery, theft with violence, snatching, armed robbery, there, either, theft, extortion, when, order, committing', 'criminal', 'Rigorous imprisonment up to ten years, and fine. If on highway, up to fourteen years.', 'Indian Penal Code, Section 392', 'central', NULL, 'act', NULL, '1224602b3e6d4be8f455ba8cbef57f1bcf048b1093a1721ba255e1b045c5b176');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '306', 'Dacoity', 'When five or more persons conjointly commit or attempt to commit a robbery, or where the whole number of persons conjointly committing or attempting to commit a robbery, and persons present and aiding such commission or attempt, amount to five or more, every person so committing, attempting, or aiding, is said to commit dacoity.', 'dacoity, gang robbery, armed gang, five or more persons, when, five, more, persons, conjointly, commit, attempt', 'criminal', 'Imprisonment for life, or rigorous imprisonment up to ten years, and fine.', 'Indian Penal Code, Section 395', 'central', NULL, 'act', NULL, '352aa880dd2ee89cb2ca4a09a461f6dfdd36983af6afac3247935d1aad073487');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '308', 'Extortion', 'Whoever intentionally puts any person in fear of any injury to that person, or to any other, and thereby dishonestly induces the person so put in fear to deliver to any person any property, or valuable security, or anything signed or sealed which may be converted into a valuable security, commits extortion.', 'extortion, blackmail, threat, fear, coercion, demand, whoever, intentionally, puts, person, injury, other', 'criminal', 'Imprisonment up to three years, or fine, or both.', 'Indian Penal Code, Section 384', 'central', NULL, 'act', NULL, 'c7edd2d67dcca1fbc8de1a7287c4b75224a60e35c7457f8223dbe66daf649f64');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '316', 'Cheating', 'Whoever, by deceiving any person, fraudulently or dishonestly induces the person so deceived to deliver any property to any person, or to consent that any person shall retain any property, or intentionally induces the person so deceived to do or omit to do anything which he would not do or omit if he were not so deceived.', 'cheating, fraud, deception, dishonesty, inducement, whoever, deceiving, person, fraudulently, dishonestly, induces, deceived', 'criminal', 'Imprisonment up to three years, or fine, or both.', 'Indian Penal Code, Section 420', 'central', NULL, 'act', NULL, '53a5abddd44021e1a916fba6b5bbcac33b2e74d104e2a0698adfec6a7d847c4b');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '318', 'Cheating and dishonestly inducing delivery of property', 'Whoever cheats and thereby dishonestly induces the person deceived to deliver any property to any person, or to make, alter or destroy the whole or any part of a valuable security, or anything which is signed or sealed and is capable of being converted into a valuable security.', 'cheating with delivery, property fraud, dishonest inducement, cheating, dishonestly, inducing, delivery, property, whoever, cheats, thereby', 'criminal', 'Imprisonment up to seven years, and fine.', 'Indian Penal Code, Section 420', 'central', NULL, 'act', NULL, '04683895b5d9916bc4beb620aa6d7e0ae0e2b04346f4c0b132816a30b82a0b24');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '329', 'Criminal Breach of Trust', 'Whoever, being in any manner entrusted with property, or with any dominion over property, dishonestly misappropriates or converts to his own use that property, or dishonestly uses or disposes of that property in violation of any direction of law prescribing the mode in which such trust is to be discharged.', 'breach of trust, misappropriation, dishonesty, fiduciary duty, embezzlement, criminal, breach, trust, whoever, being, manner, entrusted, property', 'criminal', 'Imprisonment up to five years, or fine, or both.', 'Indian Penal Code, Section 405', 'central', NULL, 'act', NULL, 'a5dc5dc05d9413161592abce402a464b44c479cbc28d8a5ff5343bd63f3e66ec');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '336', 'Forgery', 'Whoever makes any false document or false electronic record or part of a document or electronic record, with intent to cause damage or injury to the public or to any person, or to support any claim or title, or to cause any person to part with property, or to enter into any express or implied contract, commits forgery.', 'forgery, false document, fake, counterfeiting, electronic record, whoever, makes, false, document, electronic, record, part', 'criminal', 'Imprisonment up to two years, or fine, or both.', 'Indian Penal Code, Section 463', 'central', NULL, 'act', NULL, '23de36571e891ff736f786d0ee73aa371cee787b9d52272f2bcc36fd611faa25');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '351', 'Criminal Intimidation', 'Whoever threatens another with any injury to his person, reputation or property, or to the person or reputation of any one in whom that person is interested, with intent to cause alarm or to cause that person to do any act which he is not legally bound to do, commits criminal intimidation.', 'intimidation, threat, alarm, criminal threat, menace, criminal, whoever, threatens, another, injury, person, reputation', 'criminal', 'Imprisonment up to two years, or fine, or both.', 'Indian Penal Code, Section 503/506', 'central', NULL, 'act', NULL, '7cf9a6b3d05a2cea21c7a465b839642d3dd1de4274671f9d3efc3c68c520ed32');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '352', 'Intentional Insult with intent to provoke breach of peace', 'Whoever intentionally insults, and thereby gives provocation to any person, intending or knowing it to be likely that such provocation will cause him to break the public peace, or to commit any other offence.', 'insult, provocation, public peace, breach of peace, verbal abuse, intentional, intent, provoke, breach, peace, whoever, intentionally', 'criminal', 'Imprisonment up to two years, or fine, or both.', 'Indian Penal Code, Section 504', 'central', NULL, 'act', NULL, '3ee6343cb00ae63d9ccef879bab2f421e0e57342b43fe5208fd44ccd5292f4b3');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '356', 'Defamation', 'Whoever, by words either spoken or intended to be read, or by signs or by visible representations, makes or publishes any imputation concerning any person intending to harm, or knowing or having reason to believe that such imputation will harm, the reputation of such person, is said to defame that person.', 'defamation, reputation, libel, slander, imputation, character, whoever, words, either, spoken, intended, read, signs', 'criminal', 'Simple imprisonment up to two years, or fine, or both.', 'Indian Penal Code, Section 499/500', 'central', NULL, 'act', NULL, '81512ff14d70358c86a881db67a6fc7bf5a3c2e1cef81b9155b91e53ac7107c2');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '39', 'Right of Private Defence', 'Every person has a right, subject to the restrictions contained in this section, to defend his own body and the body of any other person, against any offence affecting the human body. The right of private defence extends to causing death if there is reasonable apprehension of death or grievous hurt.', 'self defence, private defence, right to defend, reasonable force, bodily harm, right, private, defence, every, person, subject, restrictions, contained', 'criminal', 'Not applicable — this section provides a defence/exception.', 'Indian Penal Code, Section 96-106', 'central', NULL, 'act', NULL, '8c103a2ba0c74a0a6e80eb1ea5bc32a59f0ecc8e894bf7e938306c7b6581fb52');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '63', 'Rape', 'A man is said to commit rape if he penetrates or performs sexual acts with a woman under circumstances falling under any of the following descriptions: against her will, without her consent, with consent obtained by putting her in fear of death or hurt, with consent obtained by impersonation of husband, when she is unable to communicate consent, or when she is under eighteen years of age.', 'rape, sexual assault, consent, sexual violence, women safety, said, commit, penetrates, performs, sexual, acts, woman', 'criminal', 'Rigorous imprisonment not less than ten years, extendable to imprisonment for life, and fine.', 'Indian Penal Code, Section 376', 'central', NULL, 'act', NULL, '96b280eeaf608c9c9e924b86c2ac8de3ab32759bae1303136731fa05ea4c24f7');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '69', 'Sexual intercourse by employing deceitful means etc.', 'Whoever, by deceitful means or making a promise to marry the woman which he does not intend to fulfil, has sexual intercourse with a woman, which is not a case of rape, shall be punished.', 'false promise of marriage, deceit, sexual intercourse, consent by fraud, cheating woman, sexual, intercourse, employing, deceitful, means, whoever, making, promise', 'criminal', 'Imprisonment up to ten years, and shall also be liable to fine.', 'No direct equivalent in IPC. New provision in BNS 2023.', 'central', NULL, 'act', NULL, '55eda6a6547c881fa8b297db09799ed2bf7903b74267593a28fe783eb086cc0b');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '70', 'Gang Rape', 'Where a woman is raped by one or more persons constituting a group or acting in furtherance of a common intention, each of those persons shall be deemed to have committed the offence of rape and shall be punished.', 'gang rape, group sexual assault, common intention, sexual violence, gang, rape, where, woman, raped, more, persons, constituting', 'criminal', 'Rigorous imprisonment not less than twenty years, extendable to life, and fine payable to victim.', 'Indian Penal Code, Section 376D', 'central', NULL, 'act', NULL, '4ed56e5c9b51e12ffcf2271c2987484379811f92aae3ae832464f5e491410fb8');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '74', 'Assault or use of criminal force to woman with intent to outrage her modesty', 'Whoever assaults or uses criminal force to any woman, intending to outrage or knowing it to be likely that he will thereby outrage her modesty, shall be punished.', 'outraging modesty, assault on woman, criminal force, molestation, eve teasing, assault, criminal, force, woman, intent, outrage, modesty, whoever', 'criminal', 'Imprisonment not less than one year extendable to five years, and fine.', 'Indian Penal Code, Section 354', 'central', NULL, 'act', NULL, '58949240cb2c8a46984d16293c556995e7ae3a47f3b3e2a1e657a4a6027dd8da');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '75', 'Sexual Harassment', 'A man committing any of the following acts: physical contact and advances involving unwelcome and explicit sexual overtures, a demand or request for sexual favours, showing pornography against the will of a woman, making sexually coloured remarks, shall be guilty of sexual harassment.', 'sexual harassment, workplace harassment, unwelcome advances, sexual remarks, sexual, harassment, committing, following, acts, physical, contact, advances', 'criminal', 'Rigorous imprisonment up to three years, or fine, or both.', 'Indian Penal Code, Section 354A', 'central', NULL, 'act', NULL, '79167bc77a98a967a5536cb8272addf015320d05794aa87053c33f78f6079cec');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '76', 'Voyeurism', 'Any man who watches or captures the image of a woman engaging in a private act in circumstances where she would usually have the expectation of not being observed either by the perpetrator or any other person.', 'voyeurism, privacy, watching, recording, private act, watches, captures, image, woman, engaging, private, circumstances', 'criminal', 'First offence: imprisonment one to three years, and fine. Second conviction: three to seven years, and fine.', 'Indian Penal Code, Section 354C', 'central', NULL, 'act', NULL, 'd17bfb102406a907e54744eeb7c656d65e44e789e881c9532b4cb9c8c7269e98');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '77', 'Stalking', 'Any man who follows a woman and contacts or attempts to contact such woman to foster personal interaction repeatedly despite a clear indication of disinterest by such woman, or monitors the use by a woman of the internet, email or any other form of electronic communication.', 'stalking, following, harassment, cyber stalking, persistent contact, follows, woman, contacts, attempts, contact, foster, personal', 'criminal', 'First offence: up to three years and fine. Second offence: up to five years and fine.', 'Indian Penal Code, Section 354D', 'central', NULL, 'act', NULL, '20550c3680792e4ab438404d3c162e4f2edddfc4af9bf2685e1e25f34620fd8c');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Nyaya Sanhita, 2023', '85', 'Cruelty by husband or relatives of husband', 'Whoever, being the husband or the relative of the husband of a woman, subjects such woman to cruelty shall be punished. Cruelty means any wilful conduct which is of such a nature as is likely to drive the woman to commit suicide or to cause grave injury or danger to life, limb or health; or harassment with a view to coercing her to meet any unlawful demand for any property or valuable security.', 'domestic violence, cruelty, dowry harassment, husband, marital cruelty, relatives, whoever, being, relative, woman, subjects', 'criminal', 'Imprisonment up to three years and fine.', 'Indian Penal Code, Section 498A', 'central', NULL, 'act', NULL, '94eef27c50f5015a3c2572f183ebd1990fe41db07b6294774b571d5de1c8a9cb');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Sakshya Adhiniyam, 2023', '101', 'Burden of proof', 'Whoever desires any Court to give judgment as to any legal right or liability dependent on the existence of facts which he asserts, must prove that those facts exist. When a person is bound to prove the existence of any fact, it is said that the burden of proof lies on that person.', 'burden of proof, evidence, legal right, assertion, court, liability, burden, proof, whoever, desires, give, judgment, legal', 'criminal', NULL, 'Indian Evidence Act, Section 101', 'central', NULL, 'act', NULL, '94a8b3943555fd52d922f5493ed76ea6c386f2cc345c106e8e84479e1874d51c');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Sakshya Adhiniyam, 2023', '104', 'Presumption of innocence', 'The prosecution must prove the guilt of the accused beyond reasonable doubt. The accused is presumed to be innocent until proven guilty. The burden of proving the guilt of the accused is on the prosecution.', 'presumption of innocence, beyond reasonable doubt, prosecution burden, accused rights, presumption, innocence, prosecution, must, prove, guilt, accused, beyond', 'criminal', NULL, 'Indian Evidence Act, Section 101-104', 'central', NULL, 'act', NULL, 'c88e58fe9c77caded3fa4f3e07ce6943ded838a47ea563ef1e237a965b17679b');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Sakshya Adhiniyam, 2023', '39', 'Relevancy of electronic records', 'Any information contained in an electronic record which is printed on a paper, stored, recorded or copied in optical or magnetic media produced by a computer shall be deemed to be a document and shall be admissible in any proceedings without further proof of the original.', 'electronic evidence, digital record, computer, admissibility, electronic document, relevancy, electronic, records, information, contained, record, printed, paper', 'criminal', NULL, 'Indian Evidence Act, Section 65B', 'central', NULL, 'act', NULL, '674f9597af0dc3660eb3a3469bc520c50bd86c23497e67f17e26ba6238d2a008');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Sakshya Adhiniyam, 2023', '47', 'Dying declaration', 'A statement, written or verbal, of relevant facts made by a person who is dead or who cannot be found, or who has become incapable of giving evidence, or whose attendance cannot be procured, is itself a relevant fact when the statement was made by a person as to the cause of his death, or as to any of the circumstances of the transaction which resulted in his death.', 'dying declaration, death statement, relevant fact, deceased, evidence, dying, declaration, statement, written, verbal, relevant, facts, made', 'criminal', NULL, 'Indian Evidence Act, Section 32', 'central', NULL, 'act', NULL, '03de2f91b5e12c890e9663907f90f590d8a9110a2e4abebd41a42fc713a5d4ff');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Bharatiya Sakshya Adhiniyam, 2023', '57', 'Confession to police officer not to be proved', 'No confession made to a police officer shall be proved as against a person accused of any offence. No confession made by any person whilst he is in the custody of a police officer, unless it be made in the immediate presence of a Magistrate, shall be proved against such person.', 'confession, police, inadmissible, magistrate, custodial statement, officer, proved, made, against, person, accused', 'criminal', NULL, 'Indian Evidence Act, Section 25/26', 'central', NULL, 'act', NULL, '7534f2eec2fed87ff64fbda4f8d7959c9137550dbd61c4bac9758a26319029ec');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Constitution of India', '14', 'Equality before law', 'The State shall not deny to any person equality before the law or the equal protection of the laws within the territory of India. This article embodies the concept of rule of law and prohibits class legislation, while permitting reasonable classification.', 'equality, equal protection, rule of law, discrimination, classification, before, state, deny, person, equal, protection, laws', 'constitutional', NULL, NULL, 'central', NULL, 'article', NULL, '2f5c9720d42af3abc3b46c98f023c07b7e0e890981c61340b934da15adcaabea');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Constitution of India', '15', 'Prohibition of discrimination on grounds of religion, race, caste, sex or place of birth', 'The State shall not discriminate against any citizen on grounds only of religion, race, caste, sex, place of birth or any of them. No citizen shall be subjected to any disability, liability, restriction or condition with regard to access to shops, public restaurants, hotels and places of public entertainment, or the use of wells, tanks, bathing ghats, roads and places of public resort maintained by the State.', 'discrimination, religion, race, caste, sex, place of birth, equality, reservation, prohibition, grounds, place, birth', 'constitutional', NULL, NULL, 'central', NULL, 'article', NULL, 'ec616b4bfae0318d325aa5a35d98609d4ec241182f36d5561e3d644c7f09ee1a');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Constitution of India', '19', 'Protection of certain rights regarding freedom of speech', 'All citizens shall have the right to freedom of speech and expression; to assemble peaceably and without arms; to form associations or unions; to move freely throughout the territory of India; to reside and settle in any part of the territory of India; and to practise any profession, or to carry on any occupation, trade or business.', 'freedom of speech, expression, assembly, association, movement, profession, fundamental rights, protection, certain, rights, regarding, freedom, speech, citizens, right', 'constitutional', NULL, NULL, 'central', NULL, 'article', NULL, '46fec64827a9ae9e855de398437c0d90959b71c4f48482c22f46d555e9a45803');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Constitution of India', '20', 'Protection in respect of conviction for offences', 'No person shall be convicted of any offence except for violation of the law in force at the time of the commission of the act charged as an offence, nor be subjected to a penalty greater than that which might have been inflicted under the law in force at the time. No person shall be prosecuted and punished for the same offence more than once. No person accused of any offence shall be compelled to be a witness against himself.', 'ex post facto law, double jeopardy, self-incrimination, conviction protection, retrospective law, protection, respect, conviction, offences, person, convicted, offence, except', 'constitutional', NULL, NULL, 'central', NULL, 'article', NULL, '6efa2f462cb7d845dded81fdde75cc2bd451b49c574d5b2568dd24a17756018a');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Constitution of India', '21', 'Protection of life and personal liberty', 'No person shall be deprived of his life or personal liberty except according to procedure established by law. This right has been expanded by the Supreme Court to include the right to live with dignity, right to privacy, right to clean environment, right to shelter, right to livelihood, and many other rights.', 'right to life, personal liberty, dignity, privacy, procedure established by law, protection, life, personal, liberty, person, deprived, except, according', 'constitutional', NULL, NULL, 'central', NULL, 'article', NULL, 'f3258763d964bf06c61b804f55b2a4d9d922b2c0af35c79126f50780d03616ee');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Constitution of India', '21A', 'Right to Education', 'The State shall provide free and compulsory education to all children of the age of six to fourteen years in such manner as the State may, by law, determine. Added by the 86th Amendment Act, 2002.', 'right to education, free education, compulsory education, children, fundamental right, right, education, state, provide, free, compulsory, fourteen', 'constitutional', NULL, NULL, 'central', NULL, 'article', NULL, '9991f4c8df29be1460ec467f79912e6eb7feaa0bb4ba314acb7c8c0b52585125');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Constitution of India', '22', 'Protection against arrest and detention in certain cases', 'No person who is arrested shall be detained in custody without being informed of the grounds for such arrest nor shall he be denied the right to consult and be defended by a legal practitioner of his choice. Every person arrested shall be produced before the nearest magistrate within twenty-four hours.', 'arrest protection, detention, grounds of arrest, legal practitioner, 24 hours, magistrate, protection, against, arrest, certain, cases, person, arrested', 'constitutional', NULL, NULL, 'central', NULL, 'article', NULL, 'b35b22d3c504254c123d08b76033f32613b1ad570d67414536645bc7aec11722');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Constitution of India', '226', 'Power of High Courts to issue writs', 'Every High Court shall have power to issue to any person or authority, including the Government, directions, orders or writs, including writs in the nature of habeas corpus, mandamus, prohibition, quo warranto and certiorari, for the enforcement of any of the fundamental rights and for any other purpose.', 'high court writ, writ jurisdiction, habeas corpus, mandamus, fundamental rights, any other purpose, power, high, courts, issue, writs, every, court, person', 'constitutional', NULL, NULL, 'central', NULL, 'article', NULL, 'ea162d513cb26912a0079e9863b6a6d030b8fc8abcfb4dc6a9284ef3a9484097');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Constitution of India', '25', 'Freedom of conscience and free profession, practice and propagation of religion', 'Subject to public order, morality and health, all persons are equally entitled to freedom of conscience and the right freely to profess, practise and propagate religion.', 'freedom of religion, conscience, propagation, religious freedom, secular, freedom, free, profession, practice, religion, subject', 'constitutional', NULL, NULL, 'central', NULL, 'article', NULL, '70d7335375a667665b9af89cd0d0ad741aec249c77e2a5e99423d1bfdcff130f');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Constitution of India', '32', 'Remedies for enforcement of fundamental rights', 'The right to move the Supreme Court by appropriate proceedings for the enforcement of fundamental rights is guaranteed. The Supreme Court shall have power to issue directions or orders or writs, including writs in the nature of habeas corpus, mandamus, prohibition, quo warranto and certiorari.', 'writ petition, supreme court, habeas corpus, mandamus, fundamental rights enforcement, remedies, enforcement, fundamental, rights, right, move, supreme, court', 'constitutional', NULL, NULL, 'central', NULL, 'article', NULL, '13842ef6d3e9edabef6e53d2240723f899d2cfef73f63820f2deb76fb4578a87');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Consumer Protection Act, 2019', '2(28', 'Definition of Misleading Advertisement', 'Misleading advertisement means any advertisement which falsely describes any goods or services, gives a false guarantee, or is likely to mislead the consumers as to the nature, substance, quantity, quality of goods or services, or conveys an express or implied representation which constitutes an unfair trade practice.', 'misleading advertisement, false advertising, unfair trade practice, consumer deception, definition, misleading, advertisement, means, falsely, describes, goods, services', 'consumer', NULL, NULL, 'central', NULL, 'act', NULL, '63c15e4ac85e680e9d8f13bd56a49e4a52c2da5a9e38c38ae256c03d19a20d2a');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Consumer Protection Act, 2019', '2(7', 'Definition of Consumer', 'Consumer means any person who buys any goods for a consideration which has been paid or promised or partly paid and partly promised, or under any system of deferred payment, and includes any user of such goods other than the person who buys such goods for resale or for any commercial purpose. It also includes a person who hires or avails of any service for a consideration.', 'consumer definition, buyer, goods, services, consideration, commercial purpose, definition, consumer, means, person, buys, paid', 'consumer', NULL, 'Consumer Protection Act 1986, Section 2(1)(d)', 'central', NULL, 'act', NULL, 'be8bfabf9cb7a6c315b7f0baec6d0bff13aa487a689972cb6db11fb5f174f8bb');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Consumer Protection Act, 2019', '34', 'District Consumer Disputes Redressal Commission', 'A complaint relating to goods or services where the value does not exceed one crore rupees shall be filed before the District Commission. The District Commission shall have the power to adjudicate complaints and provide remedies including replacement of goods, refund, compensation for losses, and punitive damages.', 'consumer complaint, district commission, consumer forum, redressal, compensation, district, consumer, disputes, commission, complaint, relating, goods', 'consumer', NULL, 'Consumer Protection Act 1986, Section 11', 'central', NULL, 'act', NULL, 'ad490f89b3ae77939ee452c8f86549a2ee777e279b20f2c365d1e85daccdb1a3');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Consumer Protection Act, 2019', '35', 'Complaints to District Commission', 'A complaint may be filed by the consumer to whom the goods are sold or delivered or agreed to be sold or delivered, or the service provided or agreed to be provided; any recognised consumer association; the Central Government or State Government; the Central Authority; or one or more consumers, where there are numerous consumers having the same interest.', 'consumer complaint, filing, district commission, who can file, class action, complaints, district, commission, complaint, filed, consumer, whom, goods', 'consumer', NULL, 'Consumer Protection Act 1986, Section 12', 'central', NULL, 'act', NULL, '9acc770def1332e7524887f28c0214ed863092341f81e4701789f61d2ce1c3df');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Consumer Protection Act, 2019', '38', 'State Consumer Disputes Redressal Commission', 'The State Commission shall have jurisdiction to entertain complaints where the value of the goods or services exceeds one crore rupees but does not exceed ten crore rupees. It also handles appeals against orders of District Commission.', 'state commission, consumer dispute, appeal, jurisdiction, one crore, ten crore, state, consumer, disputes, redressal, commission, entertain, complaints', 'consumer', NULL, 'Consumer Protection Act 1986, Section 17', 'central', NULL, 'act', NULL, 'c44141f88e132f205f1d7558dac01d256d2157c2fb3ce5d2c26bf7b01b75e6da');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Consumer Protection Act, 2019', '58', 'Product Liability', 'A product liability action may be brought by a complainant against a product manufacturer or a product service provider or a product seller for any harm caused to the consumer by a defective product manufactured by the product manufacturer. Harm includes damage to property, personal injury, illness or death.', 'product liability, defective product, manufacturer liability, harm, compensation, injury, product, liability, action, brought, complainant, against, manufacturer, service', 'consumer', NULL, NULL, 'central', NULL, 'act', NULL, '0cf7a60c9d339097c563acf3e31a91fcfdb0adca8e0fcd7863608a5a36d682dc');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Information Technology Act, 2000', '43', 'Penalty for damage to computer system', 'If any person without permission of the owner or any other person in charge of a computer, computer system or computer network, accesses or secures access, downloads, copies or extracts any data or information, introduces or causes to be introduced any computer contaminant or computer virus, damages or causes to be damaged any computer, denies or causes denial of access, he shall be liable to pay damages by way of compensation to the person so affected.', 'hacking, unauthorized access, computer damage, virus, data theft, cyber crime, penalty, damage, computer, system, person, without, permission, owner', 'cyber', 'Compensation up to five crore rupees to affected person.', NULL, 'central', NULL, 'act', NULL, 'b3ba91e265cba0b2fe0442d47c526faa75ff13e51c0f761ee41f1e026c6d0ed0');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Information Technology Act, 2000', '66', 'Computer related offences', 'If any person, dishonestly or fraudulently, does any act referred to in section 43, he shall be punishable with imprisonment for a term which may extend to three years or with fine which may extend to five lakh rupees or with both.', 'cyber crime, computer offence, hacking, dishonest, fraudulent, digital crime, computer, related, offences, person, dishonestly, fraudulently, does, referred', 'cyber', 'Imprisonment up to three years, or fine up to five lakh rupees, or both.', NULL, 'central', NULL, 'act', NULL, '8e59a7a22d0825bc006c3b72fc59f1011cfaaef25dd5ea81e714cb6927da071c');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Information Technology Act, 2000', '66A', 'Punishment for sending offensive messages (Struck down)', 'This section was struck down by the Supreme Court of India in Shreya Singhal v. Union of India (2015) as unconstitutional for violating Article 19(1)(a) of the Constitution. The section had penalized sending offensive or menacing messages through communication services.', 'offensive messages, struck down, unconstitutional, shreya singhal, free speech, online speech, punishment, sending, offensive, messages, struck, down, section, supreme', 'cyber', 'STRUCK DOWN by Supreme Court in 2015. No longer applicable.', NULL, 'central', NULL, 'act', NULL, 'cd9a386888c580b2e5467bc9dd64b98edff71dc1955bf7886aeaa92fc6e3c7fc');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Information Technology Act, 2000', '66C', 'Punishment for identity theft', 'Whoever, fraudulently or dishonestly make use of the electronic signature, password or any other unique identification feature of any other person, shall be punished.', 'identity theft, electronic signature, password theft, impersonation, fraud, punishment, identity, theft, whoever, fraudulently, dishonestly, make, electronic', 'cyber', 'Imprisonment up to three years and fine up to one lakh rupees.', NULL, 'central', NULL, 'act', NULL, '67e88fffdbd858efa91607ca5d462309f1724512c6a61c6abb869ba1b3b1c57b');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Information Technology Act, 2000', '66D', 'Punishment for cheating by personation using computer resource', 'Whoever, by means of any communication device or computer resource cheats by personation, shall be punished with imprisonment and fine.', 'online cheating, impersonation, phishing, computer fraud, personation, punishment, cheating, using, computer, resource, whoever, means', 'cyber', 'Imprisonment up to three years and fine up to one lakh rupees.', NULL, 'central', NULL, 'act', NULL, '0dedd94499a83b9fa6e1bb8f7d1546cc655d860dbe6e8f3cc1216006b7e2587e');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Information Technology Act, 2000', '66E', 'Punishment for violation of privacy', 'Whoever, intentionally or knowingly captures, publishes or transmits the image of a private area of any person without his or her consent, under circumstances violating the privacy of that person, shall be punished.', 'privacy violation, intimate images, non-consensual, voyeurism, digital privacy, punishment, violation, privacy, whoever, intentionally, knowingly, captures, publishes', 'cyber', 'Imprisonment up to three years, or fine not exceeding two lakh rupees, or both.', NULL, 'central', NULL, 'act', NULL, 'e0af41133828fd0f1e8460cd146520f770df7b50a26b3b7a3a0c9833ed7ab94d');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Information Technology Act, 2000', '67', 'Punishment for publishing or transmitting obscene material in electronic form', 'Whoever publishes or transmits or causes to be published or transmitted in the electronic form, any material which is lascivious or appeals to the prurient interest or if its effect is such as to tend to deprave and corrupt persons who are likely to read the matter.', 'obscene content, pornography, electronic form, online obscenity, publish, punishment, publishing, transmitting, obscene, material, electronic, form, whoever', 'cyber', 'First conviction: imprisonment up to three years and fine up to five lakh. Subsequent: five years and ten lakh.', NULL, 'central', NULL, 'act', NULL, 'edbd65513b56ad203470567d81f58756c9f799a8774d7a8eb6e724f8e435dde9');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Information Technology Act, 2000', '67A', 'Punishment for publishing sexually explicit material in electronic form', 'Whoever publishes or transmits or causes to be published or transmitted in the electronic form any material which contains sexually explicit act or conduct.', 'sexually explicit, electronic material, pornography, sexual content, online, punishment, publishing, sexually, explicit, material, electronic, form, whoever', 'cyber', 'First conviction: imprisonment up to five years and fine up to ten lakh. Subsequent: seven years and ten lakh.', NULL, 'central', NULL, 'act', NULL, 'd3d0a8d36dffcc31b291bd8a0618f2cba9ec8238467cf9e388948747e740cfd2');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Information Technology Act, 2000', '67B', 'Punishment for publishing child sexually explicit material in electronic form', 'Whoever publishes or transmits or causes to be published or transmitted material in electronic form which depicts children engaged in sexually explicit act or conduct, or creates text or digital images, collects, seeks, browses, downloads, advertises, promotes, exchanges or distributes material depicting children in obscene or indecent manner.', 'child pornography, csam, child exploitation, electronic material, minors, punishment, publishing, child, sexually, explicit, material, electronic, form', 'cyber', 'First conviction: imprisonment up to five years and fine up to ten lakh. Subsequent: seven years and ten lakh.', NULL, 'central', NULL, 'act', NULL, '07c7fa6c85b9aeef15fa2e34fe538d3bd82ee0f238f6e993bad44ed5b5a739c9');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Information Technology Act, 2000', '72', 'Breach of confidentiality and privacy', 'Any person who, in pursuance of any of the powers conferred under this Act, rules or regulations made thereunder, has secured access to any electronic record, book, register, correspondence, information, document or other material without the consent of the person concerned discloses such information to any other person.', 'breach of confidentiality, privacy, disclosure, unauthorized, electronic record, breach, confidentiality, person, pursuance, powers, conferred, rules', 'cyber', 'Imprisonment up to two years, or fine up to one lakh rupees, or both.', NULL, 'central', NULL, 'act', NULL, '1f18647c5a95c95abfbbe85cfe7d3efe09c1d53e55e81d420fbf65adee22c314');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Motor Vehicles Act, 1988', '112', 'Limits of speed', 'No person shall drive a motor vehicle in any public place at a speed exceeding the maximum speed or below the minimum speed fixed for the area or the class of the vehicle by the State Government.', 'speed limit, overspeeding, rash driving, traffic violation, motor vehicle speed, limits, speed, person, drive, motor, vehicle, public, place', 'motor_vehicle', 'Fine for first offence up to two thousand rupees. Second offence up to four thousand rupees.', NULL, 'central', NULL, 'act', NULL, '1426874575cf5ff5eb99676123acc68127c81f985a93d27acdad629ff89f3d5f');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Motor Vehicles Act, 1988', '140', 'Liability to pay compensation in certain cases on the principle of no fault', 'Where death or permanent disablement of any person has resulted from an accident arising out of the use of a motor vehicle, the owner of the vehicle shall be liable to pay compensation in respect of such death or permanent disablement, irrespective of fault.', 'no fault liability, motor accident, compensation, death, permanent disablement, strict liability, liability, certain, cases, principle, fault, where', 'motor_vehicle', NULL, NULL, 'central', NULL, 'act', NULL, '5a34b466679cd5367344617e0cc82e6396608da53a804c66d0b745c966754810');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Motor Vehicles Act, 1988', '166', 'Application for compensation', 'An application for compensation arising out of an accident of the nature specified in sub-section (1) of section 165 may be made by the person who has sustained the injury, or by the owner of the property, or where death has resulted from the accident, by all or any of the legal representatives of the deceased, or by any agent duly authorised by the person injured or the legal representatives of the deceased.', 'motor accident compensation, claim, injury, death, legal representatives, tribunal, application, compensation, arising, accident, nature, specified, section, made', 'motor_vehicle', NULL, NULL, 'central', NULL, 'act', NULL, 'b1660f5f71872e571c034d1adf409ad1e9008f2fef006436115b5c07d880ca63');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Motor Vehicles Act, 1988', '184', 'Driving dangerously', 'Whoever drives a motor vehicle at a speed or in a manner which is dangerous to the public, having regard to all the circumstances of the case including the nature, condition and use of the place, and the amount of traffic which at the time is or might reasonably be expected to be in the place, shall be punishable.', 'dangerous driving, rash driving, reckless driving, traffic danger, road safety, driving, dangerously, whoever, drives, motor, vehicle, speed, manner', 'motor_vehicle', 'First offence: imprisonment up to one year or fine up to five thousand or both. Subsequent: up to two years or ten thousand or both.', NULL, 'central', NULL, 'act', NULL, '260d0be628a5143e4e9beca2839285c7aa1722b0d9562d29b6d0b0325f0666de');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Motor Vehicles Act, 1988', '185', 'Driving by a drunken person or under the influence of drugs', 'Whoever, while driving or attempting to drive a motor vehicle, has in his blood alcohol exceeding 30 mg per 100 ml of blood detected in a test by a breath analyser, or is under the influence of a drug to such an extent as to be incapable of exercising proper control over the vehicle, shall be punishable.', 'drunk driving, alcohol, dui, drugs, breath analyser, blood alcohol, intoxication, driving, drunken, person, influence, whoever, while, attempting', 'motor_vehicle', 'First offence: imprisonment up to six months or fine up to ten thousand or both. Subsequent: up to two years or fifteen thousand or both.', NULL, 'central', NULL, 'act', NULL, '50138dc141bda0ede2152f88cd54dd687c51965d5bef96e474849a21329e784c');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Protection of Women from Domestic Violence Act, 2005', '12', 'Application to Magistrate', 'An aggrieved person or a Protection Officer or any other person on behalf of the aggrieved person may present an application to the Magistrate seeking relief including protection orders, residence orders, monetary relief, custody orders, and compensation orders.', 'domestic violence complaint, magistrate, protection order, residence order, monetary relief, application, aggrieved, person, protection, officer, other, behalf', 'family', NULL, NULL, 'central', NULL, 'act', NULL, '00ea856d88c6b161e06bbd37d4f53a0f0e3bae0f2bea4b89594e986f1cee288a');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Protection of Women from Domestic Violence Act, 2005', '18', 'Protection Orders', 'The Magistrate may, after giving the aggrieved person and the respondent an opportunity of being heard, pass a protection order in favour of the aggrieved person prohibiting the respondent from committing any act of domestic violence, aiding or abetting domestic violence, entering the workplace or any other place frequented by the aggrieved person, attempting to communicate in any form with the aggrieved person.', 'protection order, restraining order, domestic violence, prohibition, magistrate, no contact, protection, orders, after, giving, aggrieved, person, respondent', 'family', NULL, NULL, 'central', NULL, 'act', NULL, 'e8c68fb255f9a18252abd1863d0d0bfe6c6f91adf8e55fac33dccc115010b036');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Protection of Women from Domestic Violence Act, 2005', '19', 'Residence Orders', 'The Magistrate may, on being satisfied that domestic violence has taken place, pass a residence order restraining the respondent from dispossessing or disturbing the possession of the aggrieved person from the shared household, or directing the respondent to remove himself from the shared household.', 'residence order, shared household, dispossession, domestic violence, right to reside, residence, orders, magistrate, being, satisfied, domestic, violence, taken', 'family', NULL, NULL, 'central', NULL, 'act', NULL, '6b146823d5217e9fe08fc4aa7d438fcef03951075bd8c37d24daec7782385717');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Protection of Women from Domestic Violence Act, 2005', '20', 'Monetary Relief', 'The aggrieved person may seek monetary relief to meet the expenses incurred and losses suffered by the aggrieved person and any child of the aggrieved person as a result of domestic violence including loss of earnings, medical expenses, loss caused due to destruction or damage of property, and maintenance for the aggrieved person and her children.', 'monetary relief, maintenance, medical expenses, domestic violence compensation, financial support, monetary, relief, aggrieved, person, seek, meet, expenses, incurred', 'family', NULL, NULL, 'central', NULL, 'act', NULL, 'e831c68e6ecfe764523d4d50fb2b179deea660a52129840f117f5e78204fc6d5');
INSERT INTO law_sections (act_name, section_number, title, description, keywords, category, punishment, old_law_reference, jurisdiction, state_name, law_type, source_url, content_hash) VALUES
('Right to Information Act, 2005', '20', 'Penalties', 'Where the Central Information Commission or the State Information Commission is of the opinion that the Central Public Information Officer or the State Public Information Officer has, without any reasonable cause, refused to receive an application, or has not furnished information within the time specified, or has malafidely denied the request, it shall impose a penalty of two hundred and fifty rupees each day until the application is received or information is furnished, up to maximum of twenty-five thousand rupees.', 'rti penalty, information officer, refusal, delay, fine, twenty-five thousand, penalties, where, central, information, commission, state, opinion, public', 'constitutional', 'Penalty of Rs. 250 per day of delay, up to Rs. 25,000.', NULL, 'central', NULL, 'act', NULL, '6fcc69b910d38efa57022a2a165171479fefc0922d59dd119acffe2e08b4e93e');
